name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-basic:
    name: Test basic
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
      - name: Validate output
        shell: bash
        run: |
          source lib.sh
          cd dist
          tree .
          exists rmall/foo_0.0.0-1_rmall.ipk
          exists rm1/foo_0.0.0-1_rmall.ipk
          exists rm2/foo_0.0.0-1_rmall.ipk
          exists rmall/bar_0.0.0-1_rmall.ipk
          exists rm1/bar_0.0.0-1_rmall.ipk
          exists rm2/bar_0.0.0-1_rmall.ipk
  test-path:
    name: Test path
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: Setup test folder
        shell: bash
        run: |
          mkdir test
          cp -l package test/package
      - uses: ./
        with:
          path: ${{ github.workspace }}/test
      - name: Validate output
        shell: bash
        run: |
          source lib.sh
          cd test/dist
          tree .
          exists rmall/foo_0.0.0-1_rmall.ipk
          exists rm1/foo_0.0.0-1_rmall.ipk
          exists rm2/foo_0.0.0-1_rmall.ipk
          exists rmall/bar_0.0.0-1_rmall.ipk
          exists rm1/bar_0.0.0-1_rmall.ipk
          exists rm2/bar_0.0.0-1_rmall.ipk
  test-vebose:
    name: Test verbose
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          verbose: true
      - name: Validate output
        shell: bash
        run: |
          source lib.sh
          cd dist
          tree .
          exists rmall/foo_0.0.0-1_rmall.ipk
          exists rm1/foo_0.0.0-1_rmall.ipk
          exists rm2/foo_0.0.0-1_rmall.ipk
          exists rmall/bar_0.0.0-1_rmall.ipk
          exists rm1/bar_0.0.0-1_rmall.ipk
          exists rm2/bar_0.0.0-1_rmall.ipk
  test-arch:
    name: Test arch
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          arch: rmall
      - name: Validate output
        shell: bash
        run: |
          source lib.sh
          cd dist
          tree .
          exists rmall/foo_0.0.0-1_rmall.ipk
          missing rm1/foo_0.0.0-1_rmall.ipk
          missing rm2/foo_0.0.0-1_rmall.ipk
          exists rmall/bar_0.0.0-1_rmall.ipk
          missing rm1/bar_0.0.0-1_rmall.ipk
          missing rm2/bar_0.0.0-1_rmall.ipk
  test-package:
    name: Test package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          package: foo
      - name: Validate output
        shell: bash
        run: |
          source lib.sh
          cd dist
          tree .
          exists rmall/foo_0.0.0-1_rmall.ipk
          exists rm1/foo_0.0.0-1_rmall.ipk
          exists rm2/foo_0.0.0-1_rmall.ipk
          missing rmall/bar_0.0.0-1_rmall.ipk
          missing rm1/bar_0.0.0-1_rmall.ipk
          missing rm2/bar_0.0.0-1_rmall.ipk
  test-warnings:
    name: Test warnings
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          warnings: error
      - name: Validate output
        shell: bash
        run: |
          source lib.sh
          cd dist
          tree .
          exists rmall/foo_0.0.0-1_rmall.ipk
          exists rm1/foo_0.0.0-1_rmall.ipk
          exists rm2/foo_0.0.0-1_rmall.ipk
          exists rmall/bar_0.0.0-1_rmall.ipk
          exists rm1/bar_0.0.0-1_rmall.ipk
          exists rm2/bar_0.0.0-1_rmall.ipk
